### ISSUE TITLE
Letters of periods should appear on the schedule

### ISSUE THREAD

**Issue by antiprime** [kach/bellhop#3]
The colors don't mean anything by themselves.

**Comment by kach** [comment]
They… do. Can I see a screenshot of what you're seeing?

**Comment by antiprime** [comment]
![Screenshot](https://cloud.githubusercontent.com/assets/1058877/7804396/69c9800a-0317-11e5-8551-ca1492a84b98.png)

**Comment by zippynk** [comment]
I see the same thing... It's a Firefox/Iceweasel problem.
So is the fact that it's not A period, and G period is not coming up in 12 minutes.

@nickolas360 For now you can fix it by using an alternate web browser - try chromium, epiphany, or konqorer (I know it works in chromium, not sure about the other 2).

**Comment by kach** [comment]
@nickolas360 Eugh, gnarly. Should be fixed in the latest push (you may have to clear cache, etc.).

**Comment by antiprime** [comment]
That fixed the issue.
